package view;

import java.awt.PopupMenu;
import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author makra.zs.lili
 */
public class Dolgozok extends javax.swing.JFrame {

    /**
     * Creates new form dolgozok
     */
    public Dolgozok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        fiukVagyLanyok = new javax.swing.ButtonGroup();
        lanyokLabel = new javax.swing.JLabel();
        fiukLabel = new javax.swing.JLabel();
        lanyokCombo = new javax.swing.JComboBox<>();
        fiukCombo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lanyRadio = new javax.swing.JRadioButton();
        fiuRadio = new javax.swing.JRadioButton();
        osszesitoLabel = new javax.swing.JLabel();
        legidosebbLabel = new javax.swing.JLabel();
        osszesKorLabel = new javax.swing.JLabel();
        hatEveDolgLabel = new javax.swing.JLabel();
        legidosebb = new javax.swing.JTextField();
        osszesKor = new javax.swing.JTextField();
        hatEveDolgozo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        adatokLabel = new javax.swing.JLabel();
        korLabel = new javax.swing.JLabel();
        miotaDolgLabel = new javax.swing.JLabel();
        kor = new javax.swing.JTextField();
        miotaDolg = new javax.swing.JTextField();
        mind2nemCheckB = new javax.swing.JCheckBox();
        mentGomb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lanyokLabel.setText("Lányok");

        fiukLabel.setText("Fiúk");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("Összesítő");

        fiukVagyLanyok.add(lanyRadio);
        lanyRadio.setSelected(true);
        lanyRadio.setText("Lány");

        fiukVagyLanyok.add(fiuRadio);
        fiuRadio.setText("Fiú");

        osszesitoLabel.setText("Összesítő");

        legidosebbLabel.setText("legidősebb:");

        osszesKorLabel.setText("összes kor:");

        hatEveDolgLabel.setText("6 éve dolgozó:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(osszesKorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(osszesKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hatEveDolgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hatEveDolgozo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lanyRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fiuRadio))
                            .addComponent(osszesitoLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(legidosebbLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(legidosebb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(osszesitoLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanyRadio)
                    .addComponent(fiuRadio))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legidosebbLabel)
                    .addComponent(legidosebb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osszesKorLabel)
                    .addComponent(osszesKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hatEveDolgLabel)
                    .addComponent(hatEveDolgozo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setToolTipText("Adatok");

        adatokLabel.setText("Adatok");

        korLabel.setText("kor:");

        miotaDolgLabel.setText("mióta dolgozik:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adatokLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(korLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(miotaDolgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miotaDolg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(adatokLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korLabel)
                    .addComponent(kor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miotaDolgLabel)
                    .addComponent(miotaDolg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        mind2nemCheckB.setText("Mindkettő nem");

        mentGomb.setText("Ment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lanyokLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lanyokCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mentGomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mind2nemCheckB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fiukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(fiukCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanyokLabel)
                    .addComponent(fiukLabel)
                    .addComponent(lanyokCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiukCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mind2nemCheckB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mentGomb))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public void main() throws FileNotFoundException {

        FajlBeolvas();
        ComboFeltolt();
        RadioGombValaszt();
        FajlbaKiir();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dolgozok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel adatokLabel;
    private javax.swing.JRadioButton fiuRadio;
    private javax.swing.JComboBox<String> fiukCombo;
    private javax.swing.JLabel fiukLabel;
    private javax.swing.ButtonGroup fiukVagyLanyok;
    private javax.swing.JLabel hatEveDolgLabel;
    private javax.swing.JTextField hatEveDolgozo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kor;
    private javax.swing.JLabel korLabel;
    private javax.swing.JRadioButton lanyRadio;
    private javax.swing.JComboBox<String> lanyokCombo;
    private javax.swing.JLabel lanyokLabel;
    private javax.swing.JTextField legidosebb;
    private javax.swing.JLabel legidosebbLabel;
    private javax.swing.JButton mentGomb;
    private javax.swing.JCheckBox mind2nemCheckB;
    private javax.swing.JTextField miotaDolg;
    private javax.swing.JLabel miotaDolgLabel;
    private javax.swing.JTextField osszesKor;
    private javax.swing.JLabel osszesKorLabel;
    private javax.swing.JLabel osszesitoLabel;
    // End of variables declaration                   





    private void FajlBeolvas() throws FileNotFoundException {
        File fajl = new File("src\\model\\emberek.txt");
        Scanner sc = new Scanner(fajl);
        sc.useDelimiter(";Z");
        System.out.println(sc.next());
    }
        private void RadioGombValaszt() {
        if (fiuRadio.isSelected()) {
            legidosebb.setText("35");
            osszesKor.setText("100");
            hatEveDolgozo.setText("Róbert");
        }
        if (lanyRadio.isSelected()) {

            legidosebb.setText("33");
            osszesKor.setText("77");
            hatEveDolgozo.setText("nincs");
        }

    }
    
        private void ComboFeltolt() {
        String[] lanyok = {"Petra", "Éva", "Xénia"};
        String[] fiuk = {"Péter", "Pál", "Róbert", "Géza"};

        for (int i = 0; i < lanyok.length; i++) {
            lanyokCombo.addItem(lanyok[i]);
        }
        for (int i = 0; i < fiuk.length; i++) {
            fiukCombo.addItem(fiuk[i]);
        }
    }
    private void FajlbaKiir() throws IOException {
    String fajlNeve = "emberek.txt";
    Path path = Paths.get(fajlNeve);
    if (Files.exists(path)){
    Files.delete(path);}
    String nem = null;
    
        if (fiuRadio.isSelected()) {
            nem += "Fiúk:";
        }
        if (lanyRadio.isSelected()) {
            nem += "Lányok:";}
    
    String szoveg =
            
            legidosebb.getText().toString();
            osszesKor.getText().toString();
            hatEveDolgozo.getText().toString();
            
    Files.write(path, szoveg.getBytes());
        
    }
    
}
